### PR TITLE
add xclip to placeholders

### PR DESCRIPTION
**Pull request by supermerill**
Hi
I didn't know how to create a command line that have the content of the clipboard inside an argument, so I added the xclip command to available placeholders.

### CODE REVIEW

**Comment by bassmanitram** [comment]
Oh, I like THAT idea!!!

I'll test it!

**Comment by supermerill** [comment]
I used xclip because it's a Suggested Additional Packages and it doesn't involve any python dependencies.
I'm not sure what's available in a nautilus plugin natively.

**Comment by bassmanitram** [comment]
> I used xclip because it's a Suggested Additional Packages and it doesn't involve any python dependencies. I'm not sure what's available in a nautilus plugin natively.

Yeah understood - I'm gonna mess a bit with the implementation to see if I can get the integrated clipboard stuff to do the same thing - that might make the implementation a bit cleaner and more performant but I'll keep the same semantics you have.

*However* in order to do that, can you close this PR, then recreate it merging it into a branch I've just created ... `feature/clipboard-place-holder`.

**Review by bassmanitram — COMMENTED** [review]
Merged to feature branch for further tests

**Pull request merged**
